ServerName wordpress.coach-bg.com

# Ensure PHP files are properly handled
<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>

# Set the default handler for the main directory
<Directory /var/www/html>
    DirectoryIndex index.php
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>