http:
  middlewares:
    default-rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m
    
    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        contentSecurityPolicy: "default-src 'self'; frame-ancestors 'self'"
    
    traefik-auth:
      basicAuth:
        users:
          - "admin:$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"  # admin:password (change this)
    
    default-security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        contentSecurityPolicy: "default-src 'self'; frame-ancestors 'self'"